#ClubPI Application Configuration
#Sun Apr 13 14:06:35 WEST 2025
smtp.password=refh pozs lmni jtzu

email.from.name=Oussema Kachti
smtp.port=587
smtp.host=smtp.gmail.com
email.from.address=oussemakachti17@gmail.com
smtp.username=oussemakachti17@gmail.com
